services:
  firmware:
    build:
      context: .devcontainer/firmware
      dockerfile: Dockerfile
      args:
        - ESP_IDF_VERSTION=v5.3.2
        - TARGET_DEVICE=esp32
    volumes:
      - .:/workspaces
    command: sleep infinity

  front:
    build:
      context: .devcontainer/front
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces
    working_dir: /workspaces/front
    ports:
      - "3000:3000"
    entrypoint: ["bun"]
    command: dev

  mqtt-broker:
    image: emqx/emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"